name: Style Checks and Tests

on:
  push:
    branches:
      - '*'

jobs:
  check-style-and-run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2

    - name: Install dependencies
      run: |
        poetry config cache-dir ~/.cache/pypoetry
        poetry install --no-interaction --no-ansi

    - name: Run style checks and tests
      run: |
        poetry run nox --no-venv
